### ISSUE TITLE
Greater flexibility in repo specification

### ISSUE THREAD

**Issue by hadley** [rstudio/bookdown#1012]
Also optionally need to specify subdirectory and branch name (important for master vs main). I think making `repo` a list would make this easiest to specify in yaml:

```
bookdown::bs4_book:
  repo: 
    base: https://github.com/hadley/ggplot2-book
    branch: master
    subdir: book
```

cc @maelle
