### ISSUE TITLE
Table does not show in gitbook format (html)

### ISSUE THREAD

**Issue by drfurtado** [rstudio/bookdown#1078]
My table renders fine into PDF. But when I render the site to be viewed online, the same table does not show. I don't know what I am doing wrong.  

Any help would be greatly appreciated. 

Index.Rmd
```
--- 
title: "Teaching Stats with JASP"
author: "Ovande Furtado, Jr."
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
documentclass: book
bibliography:
- book.bib
- packages.bib
biblio-style: apalike
csl: apa-numeric-superscript-brackets.csl
link-citations: yes
description: A Guide to Data Analysis & Interpretation
site: bookdown::bookdown_site
---
```
_output.yml
```
bookdown::gitbook:
  split_bib: yes
  highlight: tango
  css: style.css
  config:
    toc:
      before: |
        <li><a href="./">Teaching Statistics with JASP</a></li>
      after: |
        <li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
    download: ["pdf", "epub"]
bookdown::pdf_book:
  includes:
    in_header: preamble.tex
  latex_engine: xelatex
  citation_package: natbib
  bilbio-style: apa_like
  keep_tex: yes
bookdown::epub_book: default
bookdown::html_book:
  css: toc.css
```
_bookdown.yml
```
book_filename: "tjs"
output_dir: "docs"
delete_merged_file: true
language:
  ui:
    chapter_name: "Chapter "
rmd_files: ["index.Rmd", "01-intro.Rmd", "02-correlation.Rmd", "03-method.Rmd","appendices.Rmd","06-references.Rmd"]
```
preamble.tex
```
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}

\ifxetex
  \usepackage{letltxmacro}
  \setlength{\XeTeXLinkMargin}{1pt}
  \LetLtxMacro\SavedIncludeGraphics\includegraphics
  \def\includegraphics#1#{% #1 catches optional stuff (star/opt. arg.)
    \IncludeGraphicsAux{#1}%
  }%
  \newcommand*{\IncludeGraphicsAux}[2]{%
    \XeTeXLinkBox{%
      \SavedIncludeGraphics#1{#2}%
    }%
  }%
\fi
```
03-method.Rmd
```
# Methods

`Something here`

```{=tex}
\begin{table}[h]
    \centering
    \caption{Independent Samples T-Test}
    \label{tab:independentSamplesT-Test}
    {
        \begin{tabular}{lrrrrrr}
            \toprule
            \multicolumn{1}{c}{} & \multicolumn{1}{c}{} & \multicolumn{1}{c}{} & \multicolumn{1}{c}{} & \multicolumn{1}{c}{} & \multicolumn{2}{c}{95\% CI for Cohen's d} \\
            \cline{6-7}
              & t & df & p & Cohen's d & Lower & Upper  \\
            \cmidrule[0.4pt]{1-7}
            engagement & 2.365 & 38 & 0.023 & 0.748 & 0.101 & 1.385  \\
            \bottomrule
            % \addlinespace[1ex]
            % \multicolumn{7}{p{0.5\linewidth}}{\textit{Note.} Student's t-test.} \\
        \end{tabular}
    }
\end{table}
```

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('bookdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/bookdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.
