### ISSUE TITLE
Copy copy button fix

### ISSUE THREAD

**Issue by hadley** [rstudio/bookdown#1086]
https://github.com/r-lib/pkgdown/commit/3574fe0aef12da059875896f5ca21f508aecaefe

**Comment by maelle** [comment]
@apreshill what's now been done in pkgdown is actually wrapping long lines. Does that sound fine for bs4_book too?

```css
pre code {
  background-color: transparent;
  white-space: pre-wrap;
  word-break: break-all;
  overflow-wrap: break-word;
}
```
