### ISSUE TITLE
Leaflet maps missing layers.png and other control icons when knitted to gitbook

### ISSUE THREAD

**Issue by jkennedyie** [rstudio/bookdown#1093]
Hi. It appears interactive leaflet maps are not output correctly by knit to gitbook. They do not render correctly in RStudio web browser, or external web browsers. They only render correctly when viewed inline within the R Studio editor. 

Sample code below. When included in a simple standalone R notebook, it renders correctly everywhere. I only find the problem when included in bookdown project and knit to gitbook.

I see other people also experience this problem: https://bookdown.org/robinlovelace/geocompr/adv-map.html#interactive-maps

Expected:
![expected](https://user-images.githubusercontent.com/1921660/110150551-4db3c600-7dd7-11eb-98d4-c7b2fb3d376a.png)

Actual:
![actual](https://user-images.githubusercontent.com/1921660/110150600-5ad0b500-7dd7-11eb-96ba-597cf1c3f751.png)

Thank you for your time.

Minimal Example:
```
library(tmap)
library(leaflet.extras)

data("World")
tmap_mode("view")

#problem 1: icon layers.png renders when knit as html but not when knit as gitbook:
tm1 <- qtm(World)
tm1

#problem 1&2: leaflet full-screen control icon renders when knit as html but not when knit as gitbook:
tm2 <- tmap_leaflet(tm1) %>% addFullscreenControl()
tm2

```

Output of `xfun::session_info('bookdown')` on my machine:

```
R version 4.0.4 (2021-02-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042), RStudio 1.4.1106

Locale:
  LC_COLLATE=English_Ireland.1252  LC_CTYPE=English_Ireland.1252    LC_MONETARY=English_Ireland.1252
  LC_NUMERIC=C                     LC_TIME=English_Ireland.1252    

Package version:
  base64enc_0.1.3   bookdown_0.21     digest_0.6.27     evaluate_0.14     glue_1.4.2        graphics_4.0.4   
  grDevices_4.0.4   highr_0.8         htmltools_0.5.1.1 jsonlite_1.7.2    knitr_1.31        magrittr_2.0.1   
  markdown_1.1      methods_4.0.4     mime_0.10         rlang_0.4.10      rmarkdown_2.7     stats_4.0.4      
  stringi_1.5.3     stringr_1.4.0     tinytex_0.30      tools_4.0.4       utils_4.0.4       xfun_0.21        
  yaml_2.2.1       
```

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('bookdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/bookdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by jkennedyie** [comment]
A mention in case @Robinlovelace came across a workaround

**Comment by cderv** [comment]
Thanks for the report ! 

This happens because of a CSS rule in `gitbook` css: 
````css
.book .book-body .page-wrapper .page-inner section.normal a {
    color: #4183c4;
    text-decoration: none;
    background: 0 0;
}
````
the background here will overwrite the rules set by leaflet: 
````css
.leaflet-control-layers-toggle {
    background-image: url(images/layers.png);
}
leaflet-bar a, .leaflet-control-layers-toggle {
    background-position: 50% 50%;
    background-repeat: no-repeat;
    display: block;
}
.leaflet-bar a, .leaflet-bar a:hover {
    background-color: #fff;
}
````

In **bookdown**, a lot of rules from leaflet will be overidden because they have a lower [specificity](https://specifishity.com/) than the one from **gitbook**. 

I am not sure how to fix that globally. If you have ideas, they are welcome.
Can leaflet have inline styling to help with this ?
