### ISSUE TITLE
Сhange the type of page switching buttons

### ISSUE THREAD

**Issue by avraam-1997** [rstudio/bookdown#1126]
Hi!

I want to switch pages with two buttons at the bottom (FOR ANY WIDTH of THE BOOK).

Example: https://adv-r.hadley.nz/preface.html or https://www.tidytextmining.com/sentiment.html

Please tell me how I can do this?

P.S.: The reason: in my bookdown, I use very wide tables and I need to use the space as efficiently as possible. I made it so that the maximum width of the page is unlimited, but then the text on the edges becomes non-clickable due to the buttons overlaid on top. I want to put them down.

**Comment by cderv** [comment]
The two book example you are linking to are made with the new `bookdown::bs4_book()`. 

It is a new format currently in dev version of **bookdown** and will be in next released version. 

If you want the style of these books you can use that and customize. They are using the new **bslib** package for Bootstrap support and customization. 

As it is very new, we haven't documented that yet in the book but you can look at the different book example and `?bookdown::bs4_book`. 

Is this what you are looking for ?

**Comment by avraam-1997** [comment]
Hi, @cderv!

Thank you for your prompt response!

I rather expected here to see a magic pill somewhere in css that allows you to configure the navigation buttons yourself so that they are always at the bottom (for example, set the width to translate from bottom to left/right in 5k ptx).

And then these buttons on the sides are very inconvenient and unnecessary for me.

P.S.: Thank you for the information about bs4_book, I will look forward to it)

**Comment by cderv** [comment]
`gitbook()` format is designed with navigation arrow on the side. You may try to use CSS / JS to remove them and create some at the bottom but I am not sure it possible or easy with the current `gitbook()` template. There is not built in way without changing the template. 

This is the kind of change that requires a new HTML template. `bs4_book()` has been created to offer a different template, more customizable as it uses bootstrap 4. 

If this new template suits you I would use this one as it has the navigation button at the bottom as you want.

**Comment by avraam-1997** [comment]
Understood, thank you, I will wait for bs4_book

**Comment by yihui** [comment]
The buttons are placed at the bottom when the page width is less than 1240px, as defined by CSS rules with the media query `@media (max-width: 1240px)`. Basically what you need to do is extract the CSS rules under that media query and apply them unconditionally:

```css
.book .book-body .navigation {
  position: static;
  top: auto;
  max-width: 50%;
  width: 50%;
  display: inline-block;
  float: left;
}
.book .book-body .body-inner {
  position: static;
  min-height: calc(100% - 50px);
}
.book .book-body .navigation.navigation-unique {
  max-width: 100%;
  width: 100%;
}
.book .book-body.fixed {
  top: 0;
}
```

If you add these rules to your custom CSS file, the buttons should appear at the bottom.
