### ISSUE TITLE
custom style not shown

### ISSUE THREAD

**Issue by moccand** [rstudio/bookdown#1132]
trying to customize output blocks according to 

https://bookdown.org/yihui/rmarkdown-cookbook/chunk-styling.html

my rendered html is OK : 

`<pre class="watch-out"><code>## 'TRIANGLE RECTANGLE'</code></pre>`

in the gitbook i always get the following style applied (seen from code inspection tool) : 

```
.book .book-body .page-wrapper .page-inner section.normal pre {
    overflow: auto;
    word-wrap: normal;
    margin: 0 0 1.275em;
    padding: .85em 1em;
    background: #f7f7f7; 
}
```
I need to comment background: #f7f7f7; (from code inspection tool) to see the color specified in the watch-out css classe.
other pieces of style defined in watch-out are applied if not already defined elsewhere (ex : text in bold)

How can i get my custom style 100% applied on top the default one ?

**Comment by cderv** [comment]
With gitbook format you need to add more class to your custom one because of CSS specificity : https://specifishity.com/

The simple CSS you set is not enough to be prioritize I think: 
```css
.watch-out {
  background-color: lightpink;
  border: 3px solid red;
  font-weight: bold;
}
```

You need to add all the gitbook classes: 
````css
.book .book-body .page-wrapper .page-inner section.normal pre.watch-out{
  background-color: lightpink;
  border: 3px solid red;
  font-weight: bold;
}
````

Or you may also force the CSS rule 

```css
.watch-out {
  background-color: lightpink !important;
  border: 3px solid red !important;
  font-weight: bold !important;
}
```

This is CSS way of working and it requires more work than our example to work in a theme more complex than the gitbook one.
