### ISSUE TITLE
Any cover-image set in YAML header should be moved to output dir

### ISSUE THREAD

**Issue by cderv** [rstudio/bookdown#1189]
It seems that when a `cover-image` is defined, it is not moved to the published folder. 
It will only be if the image itself it used in the book body. 

This should be improved IMO.

**Comment by cderv** [comment]
Using this unfortunately does not help 
````yaml
cover-image: cover.jpg
resource_files:
  - cover.jpg
````

**bookdown** may not be using `rmarkdown::find_external_resources()`
