### ISSUE TITLE
"View Book Source" link always points to the "base" dir instead of "base + subdir"

### ISSUE THREAD

**Issue by kulbhushanchand** [rstudio/bookdown#1259]
The "**View Book Source**" link at the **bottom left corner** always points to the base directory, which is fine if the docs source files resides in top level directory. However, if a subdirectory is defined for source files, **it should (ideally)** links to the "base+subdir".

**Example of my setup :** 
top level directory: https://github.com/kulbhushanchand/BioNES
book_source directory: https://github.com/kulbhushanchand/BioNES/tree/master/docs_source
build directory: https://github.com/kulbhushanchand/BioNES/tree/master/docs

**Setup:**

```
bookdown::bs4_book:
  theme:
    primary: "#637238"
  repo: 
    base: https://github.com/kulbhushanchand/BioNES
    branch: master
    subdir: docs_source
  css: style.css
```

**Link in question:**
![image](https://user-images.githubusercontent.com/17742733/133927210-c0a09365-4915-43f7-a45e-e65ccac282c1.png)
