### ISSUE TITLE
[FR] Re-visiting #1250: boolean to control collapsed navbar

### ISSUE THREAD

**Issue by walkerke** [rstudio/bookdown#1269]
Starting this new issue at the request of @cderv - 

@Pindar777 in issue #1250 requested the ability to have the third column navigation bar in a bs4_book expanded to show all H3 headings by default, as this appears nicer when printed.  This issue was solved with the new version of __bslib__ (0.3.0) which uses bootstrap 4.6.0 and includes the following CSS not found in bootstrap 4.5.3: 

```css
  .nav:not(.nav-stacked):not(.flex-column) {
    float: none !important
  }
  .nav:not(.nav-stacked):not(.flex-column)>.bslib-nav-spacer {
    margin-left: auto !important
  }
  .nav:not(.nav-stacked):not(.flex-column)>.form-inline {
    margin-top: auto;
    margin-bottom: auto
  }  
```

For my purposes (and others with whom I have spoken about this), the __old__ behavior is preferable, especially for chapters that include a lot of H3 headers.  For example, here is a chapter from my book the __old__ way, where only the active H2 is expanded on the right-hand side: 

![image](https://user-images.githubusercontent.com/4872833/137019243-aab0dd73-6b51-481a-8e94-4c7818f2a054.png)

Here is the same chapter the __new__ way, which expands every H2 header by default, making the view messier (in my opinion): 

![image](https://user-images.githubusercontent.com/4872833/137019367-5a52e7a8-47f8-4333-a578-ea63c5ab2e17.png)

I've fixed the problem temporarily by rolling back to __bslib__ version 0.2.4, which defaults to the older Bootstrap version.  Another solution would be to remove the new CSS section manually.  However, this isn't likely to be a stable solution longer-term as authors will want to take advantage of new features in __bslib__ and Bootstrap.  I've tagged this as a feature request if you all think this would be a priority to solve.  If not - does anyone know of a quick solution that already exists that non-CSS experts like me could take advantage of?  

Thank you!
