### ISSUE TITLE
Data-latex is ignored by bookdown::beamer_presentation2

### ISSUE THREAD

**Issue by finkelshtein** [rstudio/bookdown#1285]
Hi,

I have an issue with fenced theorems. The following .Rmd file is knitted as expected:
````
---
title: "book"
documentclass: beamer
output: 
    beamer_presentation:
      keep_tex: true
      toc: no
      latex_engine: xelatex
      theme: Warsaw
      citation_package: natbib
      template: null
link-citations: yes
colorlinks: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Slide name

:::{.theorem data-latex='[Name of Theorem]'}
Text of Theorem
:::

:::{.fact data-latex='[Name of Fact]'}
Text of Fact
:::
````
so that in the pdf I can see "Theorem (Name of Theorem)" and "Fact (Name of Fact)".

However, if I replace in the output `beamer_presentation:` by `bookdown::beamer_presentation2:`, I can see in the console 
```
[WARNING] data-latex attribute can't be used with one of bookdown custom environment. It has been removed.
```
and the pdf does not contain "(Name of Theorem)". 

I guess the lua-filter 'latex-div.lua' removed this, because, for some reason, the FORMAT here is neither 'latex' nor 'beamer', but I don't know how to change this.

Moreover, the same issue happens if I use the following 'exotic' output (I need to have a book consisted of beamer slides):
```
output:
    bookdown::pdf_book:
      base_format: rmarkdown::beamer_presentation
      number_sections: false
```

The output of `xfun::session_info('bookdown')` is as follows:
```
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042), RStudio 2021.9.0.351

Locale:
  LC_COLLATE=English_United Kingdom.1252 
  LC_CTYPE=English_United Kingdom.1252   
  LC_MONETARY=English_United Kingdom.1252
  LC_NUMERIC=C                           
  LC_TIME=English_United Kingdom.1252    

Package version:
  base64enc_0.1.3 bookdown_0.24.3 digest_0.6.28  
  evaluate_0.14   fastmap_1.1.0   glue_1.4.2     
  graphics_4.1.1  grDevices_4.1.1 highr_0.9      
  htmltools_0.5.2 jquerylib_0.1.4 jsonlite_1.7.2 
  knitr_1.36.7    magrittr_2.0.1  methods_4.1.1  
  rlang_0.4.12    rmarkdown_2.11  stats_4.1.1    
  stringi_1.7.5   stringr_1.4.0   tinytex_0.35   
  tools_4.1.1     utils_4.1.1     xfun_0.27      
  yaml_2.2.1
```

Regards,
Dmitri
