### ISSUE TITLE
v0.25 breaks collapsible TOC?

### ISSUE THREAD

**Issue by cmadland** [rstudio/bookdown#1330]
I've upgraded to bookdown v0.25 and it doesn't seem to render the TOC with sections collapsed.

```
bookdown::gitbook:
  includes:
      in_header: includes.html
  css: style.css
  config:
    toc:
      collapse: section
      scroll_highlight: true
      before: |
        <li><a href="https://otessa.org" target="blank">OTESSA</a></li>
      after: |
        <li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>
    edit: https://github.com/otessa/2022/edit/master/%s
    download: ["epub"]
bookdown::epub_book: default
```
renders to this

<img width="465" alt="image" src="https://user-images.githubusercontent.com/12282929/163273616-1b84c91c-d831-43f7-89c1-575d59a05c8a.png">

Here is a sample of how the HTML output has changed

![image](https://user-images.githubusercontent.com/12282929/163274239-c17c6fbc-f27a-4552-94b4-5e92554391af.png)

Let me know if you need any other info.
