### ISSUE TITLE
Cross-references don't work in HTML output if reference is in another file

### ISSUE THREAD

**Issue by piiskop** [rstudio/bookdown#1337]
In one RMD-file _mechanics-rules.Rmd_, i have:

````
```{=tex}
\begin{equation}
d(\overrightarrow{s}) = \overrightarrow{v} \cdot d(t),
(\#eq:smallest-distance)
\end{equation}
```
````
In another RMD-file _mechanics.Rmd_, i have:

````
\@ref(eq:smallest-distance)
````

In the [output](http://physics.tennis24.ee/mechanics.html#146_Kraana), i see:

> [(??)](http://physics.tennis24.ee/mechanics.html#eq:smallest-distance)

**Comment by cderv** [comment]
Hi, 

Can you format your issue correctly so that it is easier to read and understand ? 
https://yihui.org/issue/#please-format-your-issue-correctly

Thank you !

**Comment by piiskop** [comment]
Done.

**Comment by cderv** [comment]
Which output format are you using ? It seems to work correctly in `gitbook()` but I think you don't use that one. 

thanks

**Comment by piiskop** [comment]
````
title: "Mehaanika ülesanded: sirgjooneline liikumine"
output:
  bookdown::html_document2:
    toc: yes
    toc_float: yes
    toc_depth: 5
bibliography: references.bib
biblio-style: "newapa"
link-citations: true
citation_package: biblatex
````
