### ISSUE TITLE
Multiple PDF outputs

### ISSUE THREAD

**Issue by thosgood** [rstudio/bookdown#1344]
I am using bookdown to build a site that also has a PDF version, generated using a latex template: my build file has

```bash
R -e "bookdown::render_book('index.Rmd','bookdown::gitbook',config_file = '_bookdown.yml')"
R -e "bookdown::render_book('index.Rmd','bookdown::pdf_book',config_file = '_bookdown.yml')"
```

and my `index.Rmd` has

```yaml
output:
  bookdown::gitbook:
    split_by: section+number
    config:
      toc:
      download: ["pdf"]
      ... (etc) ...
  bookdown::pdf_book:
    template: a4-latex-template.tex
    latex_engine: xelatex
    keep_tex: yes
```

I would like to generate another PDF version, using a different `.tex` template file, so I end up with the HTML version and two PDFs. I can't find any details on how to do this online, and I tried passing the `template` key directly into `bookdown::render_book()`, but this seems to not be allowed.
