### ISSUE TITLE
TOC depth int bs4_book

### ISSUE THREAD

**Issue by karlmay88** [rstudio/bookdown#1377]
Hi there,

I am wondering whether there is a way to increase the TOC depth in bs4_book? It looks as if my current toc setting do not have any effect. This is the content of `_output.yml`
```
bookdown::bs4_book:
  toc_depth: 6
  theme:
    primary: "#0d6efd"   
       base_font: 
      google: Sen
    heading_font:
      google:
        family: Bitter
        wght: 200
    code_font:
      google: 
        # arguments to sass::font_google() 
        family: DM Mono
        local: false
```
