### ISSUE TITLE
Self-defined reference style does not take effect in PDF output

### ISSUE THREAD

**Issue by huangwb8** [rstudio/bookdown#1384]
Here is my yaml head of `index.Rmd`:

```yaml
--- 
title: "abcdefg"
author: "Bensz"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
csl: briefings-in-bioinformatics.csl
link-citations: yes
geometry:
  - top=1in
  - left=1in
  - right=1in
  - bottom=1in
fontsize: 12pt
linestretch: 1.5
linkcolor: "blue"
description: "abcdefg"
---
```

Here is the settings in the file `_output.yml`:

```yaml
bookdown::gitbook:
  css: style.css
  config:
    toc:
      before: |
        <li><a href="./">abcdefg</a></li>
      after: |
        <li><a href="https://blognas.hwb0307.com/" target="blank">Welcome to My Blog!</a></li>
    download: ["pdf", "epub"]


bookdown::pdf_book:
  includes:
    in_header: preamble.tex
  latex_engine: xelatex
  citation_package: natbib
  pandoc_args: [
      "--bibliography=book.bib",
      "--csl=briefings-in-bioinformatics.csl",
    ]
  keep_tex: yes
  toc: TRUE
  toc_depth: 3
```
After building book, I found the reference format only take effect in `gitbook` but not in `pdf_book`. Is any setting I ignored before?

Any suggestions? Thank you very much!
