### ISSUE TITLE
Separate `rmd_files:`

### ISSUE THREAD

**Issue by ismayc** [rstudio/bookdown#177]
I am trying to specify different files to knit for a LaTeX pdf and for a gitbook, but I am unable to get it to work.

When I run,

```yaml
rmd_files:
  html: ["index.Rmd", "abstract.Rmd", "intro.Rmd"]
  latex: ["abstract.Rmd", "intro.Rmd"]
```

It compiles all three documents whether I choose `pdf_book` or `gitbook`.  I can specify that only two files be included:

```yaml
rmd_files: ["index.Rmd", "abstract.Rmd"]
```

But I'd really like to be able to customize as is specified at https://bookdown.org/yihui/bookdown/usage.html.
