### ISSUE TITLE
Make render_book() work?

### ISSUE THREAD

**Issue by hadley** [rstudio/bookdown#22]
By looking for `_bookdown.yml` in current directory, and adding document format metadata to it as well.

**Comment by yihui** [comment]
Sorry I didn't get this one. Add document format metadata to what?

**Comment by hadley** [comment]
I think for `render_book()` to work without a path to a specific file, you'd need to move the output related metadata to `_bookdown.yml`, i.e.

```yaml
output:
  bookdown::html_chapters:
    lib_dir: "book_assets"
    toc_depth: 1
    html_names: "chapter"
```
