### ISSUE TITLE
i18n feature is not working 

### ISSUE THREAD

**Issue by axitdn** [rstudio/bookdown#232]
I have changed _bookdown.yaml file content to this:

```yaml
book_filename: 'bookdown-demo'
chapter_name: 'Chương '
language:
  label:
    fig: 'Hình '
    tab: 'Bảng '
    eq: 'Equation '
    thm: 'Theorem '
    lem: 'Lemma '
    def: 'Definition '
    cor: 'Corollary '
    prp: 'Proposition '
    ex: 'Example '
    proof: 'Proof. '
    remark: 'Remark. '
  ui:
    edit: Edit
    chapter: ''

```

When I build gitbook from RStudio there are no changes happen in my book. 
// fig and tab still are Figure x.x and Table x.x. 
However, chapter_name has changed to "Chương " in gitbook but it disapears in epub book format.
