### ISSUE TITLE
Disqus layout issues in wide screen

### ISSUE THREAD

**Issue by pssguy** [rstudio/bookdown#235]
In wide screen, adding Disqus results in this look
![disqus2](https://cloud.githubusercontent.com/assets/2775918/19822347/cf9ebb8e-9d17-11e6-9a23-f89e01e04c1c.png)

Narrowing browser window produces a correct look
![disqus1](https://cloud.githubusercontent.com/assets/2775918/19822367/e4a18c14-9d17-11e6-97a3-ef0e9393325b.png)

Here is the _output.yml code

```
bookdown::gitbook:
  css: styles.css 
  config:
    toc:
      collapse: section
    download: [pdf, epub]  
  includes:
      after_body: disqus.html 

````
