### ISSUE TITLE
Include build tip in docs

### ISSUE THREAD

**Issue by hadley** [rstudio/bookdown#24]
Create a `_build.sh` that contains:

```R
#!/usr/bin/env Rscript
bookdown::render_book("index.rmd")
```

Then `chmod +x _build.sh`

Then In RStudio, you can map `Cmd + Shift + B` to build the complete book by going to project options, build tools, select custom and then selecting `_build.sh`.

@jjallaire will this always get you the version of R that's running in RSudio?

**Comment by hadley** [comment]
That also makes travis setup simple:

```R
language: R
cache: packages

script: _build.sh
```

**Comment by hadley** [comment]
Or maybe:

```yaml
language: R
cache:
  packages: true
  directories:
  - *_cache
  - *_files

script: _build.sh
```
