### ISSUE TITLE
How to use a html template with gitbook

### ISSUE THREAD

**Issue by benmarwick** [rstudio/bookdown#265]
I'm looking at some information about using templates here:  https://bookdown.org/yihui/bookdown/templates.html, but I'm not sure where to set the configuration to point the build process to a local template file. I [see](https://github.com/robjhyndman/monashthesis) that templates are used with PDF output:

```
bookdown::pdf_book:
   template: monashthesis.tex
``` 

But if I use `template:` similar to this, directly under `bookdown::gitbook:`, I get an error:
```
bookdown::pdf_book:
  includes:
    in_header: preamble.tex
  latex_engine: xelatex
  citation_package: natbib
  keep_tex: yes
bookdown::epub_book: default
bookdown::gitbook:
  template: my_template.html
  css: style.css
  config:
    toc:
      before: |
        <li><a href="./">A Minimal Book Example</a></li>
      after: |
        <li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
    edit: https://github.com/rstudio/bookdown-demo/edit/master/%s
```
like so:

```
Error in rmarkdown::html_document(..., extra_dependencies = c(extra_dependencies,  : 
  formal argument "template" matched by multiple actual arguments
Calls: <Anonymous> ... do.call -> <Anonymous> -> html_document2 -> <Anonymous>
Execution halted
Error in eval(expr, envir, enclos) : 
  Failed to compile the book to bookdown::gitbook
```
And this occurs when my_template.html is the same file that we see at `bookdown:::bookdown_file("templates/default.html")`

I can put it after `config:`, but that doesn't seem to have any effect on the results. 

My motivation for using a custom html template is to insert a custom block at the top and bottom of each html page of my book. I'm guessing that a template with those blocks is the simplest way, but I'm happy to take advice!
