### ISSUE TITLE
how can I change the biblio style

### ISSUE THREAD

**Issue by dapengde** [rstudio/bookdown#354]
In the demo file a biblio style of apalike can be found in index.Rmd:

```
biblio-style: apalike
```

When I change it into `plain` or `ieeetr`, the citation style in the output gitbook files does not change.  Has anyone encountered this problem?

**Comment by yihui** [comment]
`biblio-style` is only applied to LaTeX output. For other output formats, you need to use the `csl` option in YAML or `--csl` in `pandoc_args`: http://pandoc.org/MANUAL.html#citations

**Comment by pa0** [comment]
Where I should add CSL file?
In _output.yml adding the line:
`pandoc_args: "--csl = apa_pl.csl"`
generates error 2 in pandoc (unrecognized option) :-(

**Comment by pa0** [comment]
Solved:

right format is:

`  pandoc_args: [
    "--csl", "apa_pl.csl"
    ]
`

**Comment by wasmetqall** [comment]
@pa0 
I have tried your solution by adding the code to yaml, but it didn't work.

**Comment by pa0** [comment]
Did You put CSL file in folder with your.rmd or in papaja folder? I have in both places :-)

**Comment by TianyiShi2001** [comment]
I have the same problem. Worse, the style in PDF output does not change. I checked the .tex file and it's not actually using bibtex directly. Instead, it converts citations into cross-references:

```
本书为R(R Core Team \protect\hyperlink{ref-R-base}{2019})和tidyverse(Wickham \protect\hyperlink{ref-R-tidyverse}{2017})的入门向教程。
```

```
\leavevmode\hypertarget{ref-R-base}{}%
R Core Team. 2019. \emph{R: A Language and Environment for Statistical Computing}. Vienna, Austria: R Foundation for Statistical Computing. \url{https://www.R-project.org/}.
```

My YAML:

```
---
---
title: "foo"
author: "bar"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    includes:
      in_header: partials/header.html
  bookdown::pdf_book:
    keep_tex: yes
    latex_engine: "xelatex"
    includes:
      in_header: partials/header.tex
bibliography: ["bib/main.bib", "bib/packages.bib"]
biblio-style: ieeetr
link-citations: true
documentclass: book
---
```

and tex header:

```
\usepackage[UTF8]{ctex}
```
