### ISSUE TITLE
Can not use notebook format features with a regular plain .html extension

### ISSUE THREAD

**Issue by devereaux** [rstudio/bookdown#399]
As suggested in https://bookdown.org/yihui/bookdown/a-single-document.html I use html_document2() to write reports with bookdown which provides cross reference features.

I also like to embed the Rmd and have code chunks,  to be be collapsible, so I use:

```yaml
  bookdown::html_document2:
    base_format: rmarkdown::html_notebook
    code_folding: hide
```

However, knitting to html_document2 saves the file using the ".nb.html" extension imported from html_notebook. Doing a regular File/Save within RStudio overwrites this file.

It would be nice to add an option to support a regular ".html" extension, so that the File/Save would only overwrite the source file.Rmd and the preview file.nb.html
