### ISSUE TITLE
support katex

### ISSUE THREAD

**Issue by laoshaw** [rstudio/bookdown#401]
This is really a feature request, please adding Katex support as it is replacing all other math rendering these days, it's also very fast and easy to use.

**Comment by yihui** [comment]
Thanks! I'll consider it in the future. KaTeX is indeed very fast, but it only covers a subset of MathJax's LaTeX commands and environments: https://github.com/Khan/KaTeX/wiki/Function-Support-in-KaTeX For example, there is no `equation` environment.

**Comment by py9mrg** [comment]
I'd love this feature, too.

While I accept that KaTeX has some limitations, an option to switch between MathJax and KaTeX, similar to what is done by the [prettydoc](https://github.com/yixuan/prettydoc/) package would be great:

```
title: Nineteen Years Later
author: Harry Potter
date: July 31, 2016
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
    math: katex
```

If you're wondering why I don't just use that package - it's because I'd prefer to be able to switch to KaTeX using arbitrary themes, but I don't seem to be able to - easily - get that package working in anything but the themes they've provided. Maybe I'm being dumb, but it's not as easy as deleting the `theme` and `highlight` lines, to revert back to the standard html output.
