### ISSUE TITLE
request: new behavior of gitbook toc collapse

### ISSUE THREAD

**Issue by brooksambrose** [rstudio/bookdown#556]
First, love the package thanks!

The collapse setting for gitbook is great, but currently it takes two clicks on a collapsed heading to open it if the heading is also a separate html page. If you click on the TOC element that is collapsed, and the page loads, it will not unfurl unless the heading is clicked on again. `collapse: section` with `split_by: section` for instance says that on page load it should be collapsed, but in the case of a direct click on the heading leading to a page load, it would be natural for the clicked section to unfurl.

Another idea would be to have any section unfurl whenever a section is highlighted as in `scroll_highlight: yes` regardless of whether it is clicked on or not. A sensible default would imho be that currently viewed content should be unfurled in the TOC, while content that is not on screen should be furled.

Sorry if this is doable already, and thanks in advance for your advice!

**Comment by yihui** [comment]
That sounds like reasonable advice to me, but I guess I won't have time to implement it until after this summer. If you are able to implement it by yourself, a pull request will be welcome! :)

**Comment by ferroao** [comment]
Is this the same problem I have doing this:

After cloning the bookdown-demo. I want to use the toggle function of sections.

For this, I modified the file _output.yml adding the collapse line:

bookdown::gitbook:
  config:
    toc:
      collapse: section

And added some sections in index.Rmd

# Prerequisites

## second

### third

After building the book in Rstudio, with:
bookdown::render_book("index.Rmd", "bookdown::gitbook")

It works with a little defect. When I click chapters without sections, and also sometimes the chapter with sections, there is a rapid movement of the menu as if it opens and immediately closes the sections.

Does it have a solution?

**Comment by cderv** [comment]
Just some note while reading this issue: 

* Reproduce by cloning bookdown-demo
* Add in `_output.yml` split by and toc.collapse
```yaml
bookdown::gitbook:
  css: style.css
  split_by: section
  config:
    toc:
      before: |
        <li><a href="./">A Minimal Book Example</a></li>
      after: |
        <li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
      collapse: section
    edit: https://github.com/rstudio/bookdown-demo/edit/master/%s
    download: ["pdf", "epub"]
```
* Add this in `04-application.Rmd`
````markdown
# Applications

Some _significant_ applications are demonstrated in this chapter.

## Example one

### subitem 1

## Example two

### subitem 2
````
* Build the book in gitbook

Here is the behavior that could be improve: 
![toc-gitbook](https://user-images.githubusercontent.com/6791940/112008781-173fb000-8b26-11eb-9c5b-5f9809ff45c4.gif)

* When a menu under Application is clicked, the submenu should also unfold.
