### ISSUE TITLE
feature request: option to restart endnote numbering after each GitBook-style web chapter

### ISSUE THREAD

**Issue by JackDougherty** [rstudio/bookdown#589]
Thanks for bookdown! I previously posted [this question on StackOverflow](https://stackoverflow.com/questions/50616517/restart-endnote-numbering-after-each-gitbook-style-web-chapter-in-r-bookdown) and offered a bounty, but did not receive any answers, so am adding as a feature request here.

I am preparing an historical book manuscript, written in R-Markdown with Bookdown, which will have 8 chapters, each with 100+ Chicago-style endnotes, using the GitBook-style web format.

My goal is to restart endnote numbering after each chapter, to avoid running into high digits and to resemble the appearance of traditional history books.

I have experimented with most of the settings described here (https://bookdown.org/yihui/bookdown/html.html#gitbook-style), but cannot produce the desired web output. Here's the relevant portion of my index.Rmd:

```
output:
  bookdown::gitbook:
    dev: svglite
    css: css/style.css
    split_by: rmd
    split_bib: true
```
See my simplified mockup demo: https://jackdougherty.github.io/bookdown-test/book/ and source code: https://github.com/JackDougherty/bookdown-test

**Comment by yihui** [comment]
This can be a good and interesting JavaScript challenge, but I have no time to take it.

**Comment by JackDougherty** [comment]
Thanks @romles for creating this solution in style.css, described here:
https://stackoverflow.com/questions/50616517/restart-endnote-numbering-after-each-gitbook-style-web-chapter-in-r-bookdown

Demo here:
https://jackdougherty.github.io/bookdown-test/book

If @yihui approves, please consider adding to bookdown code for others.

/* footnote counter to restart numbering for each chapter */

 /* don't show the wrong footnote calls */
 .footnote-ref sup {
   display: none;
 }

 /* use a counter for footnote calls */
 .level1 {
   counter-reset: fn-call;
 }

 .footnote-ref {
   counter-increment: fn-call;
 }

 /* generate new footnote calls */
 .footnote-ref::after {
   content: counter(fn-call);
   position: relative;
   top: -.5em;
   font-size: 85%;
   line-height: 0;
   vertical-align: baseline;
 }

 /* use a counter for footnotes numbering */
 .footnotes ol {
   list-style: none;
   counter-reset: fn-number;
 }

 .footnotes li {
   counter-increment: fn-number;
 }

 .footnotes p::before {
   content: counter(fn-number) '. ';
 }

**Comment by ilyankou** [comment]
@JackDougherty Version 0.9 came with some changes to CSS, that's why the CSS tweak described two comments above https://github.com/rstudio/bookdown/issues/589#issuecomment-441386205 doesn't work as desired.

The <a> tag's class inside the citation changed from ___.footnote-ref___ to ___.footnoteRef___. So you need to extend some of your CSS to account for that:

```css
/* don't show the wrong footnote calls */
.footnote-ref sup,
.footnoteRef sup {
  display: none;
}

...

.footnote-ref,
.footnoteRef {
  counter-increment: fn-call;
}

.footnote-ref::after,
.footnoteRef::after {
content: counter(fn-call);
position: relative;
top: -.5em;
font-size: 85%;
line-height: 0;
vertical-align: baseline;
}

...
```
