### ISSUE TITLE
Wrong navigation next reference link when set '-ascii_identifiers' on Windows

### ISSUE THREAD

**Issue by psychelzh** [rstudio/bookdown#605]
A minimal example with two files:

`index.Rmd`:

```r
---
title: "测试"
---

# 前言

这里要介绍这本书主要要讲什么。
```

`01.Rmd`:

```r
# 测试章节

本来这里要将重要内容的。
```

And one output configuration `yaml` file:

```yaml
bookdown::gitbook:
  lib_dir: "book_assets"
  split_by: section
  md_extensions: -ascii_identifiers
```

After build the book on Windows OS, the navigation-next reference link in `index.html` is as follow:

```html
<a href="娴嬭瘯绔犺妭.html" class="navigation navigation-next navigation-unique" aria-label="Next page"><i class="fa fa-angle-right"></i></a>
```

The characters "**测试章节**" were badly encoded. 

What's more, this is not an issue on `Linux` OS environment.
