### ISSUE TITLE
怎么在word中对图表按章节编号？

### ISSUE THREAD

**Issue by ShixiangWang** [rstudio/bookdown#626]
益辉你好 @yihui，

我用的是你提供的中文模板，输出html和pdf都很nice，但因为当前工作需要输出的是word，我发现word不能对图表自动按章节编号，有没有什么简单的办法呢？

我在提问前搜了下google和查看了bookdown相关的issue，好像pandoc没有提供自动给word章节编号、表格编号的功能？所以我现在想到的办法是自己手打，但输出的文字前又会带图表序号。

![image](https://user-images.githubusercontent.com/25057508/45250095-06abfd80-b35f-11e8-8713-3fb5cf23bd94.png)

```
book_filename: bookdown
clean: [packages.bib, bookdown.bbl]
language:
  label:
    fig: ""
    tab: ""
  ui:
    edit: "编辑"
    chapter_name: ["第 ", " 章"]
```

我修改了下`fig`和`tab`还是会带序号。

![image](https://user-images.githubusercontent.com/25057508/45250123-8df97100-b35f-11e8-9676-2c2cbed16081.png)
