### ISSUE TITLE
MathJax info shown in references

### ISSUE THREAD

**Issue by topepo** [rstudio/bookdown#683]
The [FES references](https://bookdown.org/max/FES/references.html) contain a dump of MathJax

The References.Rmd file is 

```r
`r if (knitr:::is_html_output()) '
# References {-}
'`
```

**Comment by yihui** [comment]
I cannot tell what happened without the source or a minimal reproducible example...

**Comment by topepo** [comment]
Finally got around to making one: [`https://github.com/topepo/MathJax-test`](https://github.com/topepo/MathJax-test).

**Comment by yihui** [comment]
Thanks for the example! I'm able to reproduce the issue, although I don't have an idea why this occurs at the moment.

**Comment by RLesur** [comment]
I think the problem comes from **rmarkdown**.
I found a little bug in **rmarkdown** when a HTML document is rendered with `self_contained: false` and `mathjax: <some_url>`.
For now, here is a turnaround for this bug. In https://github.com/topepo/MathJax-test/blob/master/_output.yml, you can use these arguments:
```yaml
bookdown::gitbook:
  css: FES.css
  dev: svglite
  split_by: section
  mathjax: null
  pandoc_args: --mathjax=https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-MML-AM_HTMLorMML.js
```
I will open a PR in **rmarkdown** to fix this bug.
