### ISSUE TITLE
Special character does not show up in bibliography (but works in body)

### ISSUE THREAD

**Issue by lnalborczyk** [rstudio/bookdown#717]
Hi,

NB: I have asked [a question on SO](https://stackoverflow.com/questions/55342838/special-character-does-not-show-up-in-bibliography-but-works-in-body-in-bookdo) that remained unanswered so I'm opening an issue here.

I am writing my dissertation with `bookdown` and the `memoir` class in `R`. I need to include special characters such as "\oe". This character appears correctly in the body of the document (therefore it's NOT a font problem).

However, the same character does not appear in the bibliography section. More precisely, nothing appears instead of the special character. The .bib file is a .tex generated by Zotero where the "\oe" symbol (for instance) is represented as "Å".

I have disabled citation packages in order to format the bibliography section following a specific citation style (i.e., I am using the apa6.csl), so the problem might come from there. However, I am also regularly writing articles in RMarkdown using this same csl file (and using the [`papaja` package](https://github.com/crsh/papaja)) and this never happened before, so it seems to be specific to `bookdown`...

It is difficult to provide a reproducible example though, as I am working from my messy dissertation repository. But here is (a part of) my `_output.yml `file:

```
bookdown::pdf_book:
  includes:
    in_header: latex/preamble.tex # defines style and latex options
    before_body: latex/before_body.tex # defines cover page
  latex_engine: xelatex # lualatex or xelatex
  citation_package: none # needs to be "none" in order to use the csl file
  keep_tex: true # keeps the .tex file
  dev: "cairo_pdf"
  toc: false # deactivates default table of contents
  highlight: pygments # code highlighting
  pandoc_args: [ "--csl", "./csl/apa6.csl" ] # specifies the csl file to be used
```

Any idea ?
