### ISSUE TITLE
Cannot customize Appendix prefix using a user-defined function

### ISSUE THREAD

**Issue by jooyoungseo** [rstudio/bookdown#825]
Thanks for the recent change through #783; however, I found an issue.

I wanted to make my Appendix format such as `Appendix A: Title`, `Appendix A.1: Title`, `Appendix B: Title` ...

Thus, I added the following line in _bookdown.yml:

``` yaml
language:
  ui:
    appendix_name: !expr function(i) {paste0('Appendix ', i, ':', ' ')}
```

However, when I render the book using `bookdown::render_book("index.Rmd", output_format = "bookdown::gitbook")`, it throws the following error:

> Error in prefix != "" :                                                                                                                                
> comparison (2) is possible only for atomic and list types                                                                                            
> Calls: <Anonymous> ... split_chapters -> restore_appendix_html -> number_appendix                                                                      

FYI, there's no issue with the same syntax for `chapter_name` field when tested.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!

**Comment by yihui** [comment]
Note that in your case, you can also use a vector instead of a function:

```yaml
language:
  ui:
    appendix_name: ["Appendix ", ":"]
```
