### ISSUE TITLE
link-citations cannot be applied separately for different output formats

### ISSUE THREAD

**Issue by jooyoungseo** [rstudio/bookdown#836]
I have confirmed that `link-citations` option cannot be applied separately for different output formats.

Let's say I want to set it to `true` for `bookdown::gitbook` output; but `false` for `bookdown::word_document2`.

So I did the following:

\_output.yml

```yaml
bookdown::gitbook:
  link-citations: true
bookdown::word_document2:
  link-citations: false
```

However, it does not work, which means citations are not linked in both outputs.

I have even tried with the following syntax:

\_output.yml

```yaml
bookdown::gitbook:
  pandoc_args: --metadata link-citations=true
bookdown::word_document2:
  pandoc_args: --metadata link-citations=false
```

This time; however, `--metadata link-citations` flag is interpreted as an unknown option.

I have used `pandoc` v2.8.1, the latest version as of this writing.
