### ISSUE TITLE
Gitbook toolbar for downloading files

### ISSUE THREAD

**Issue by antaldaniel** [rstudio/bookdown#854]
I have tried to modify the _`output.yml ` file like this

`download: [ ["book.pdf", "PDF"], ["book.epub", "EPUB"], ["book.docx", "Word"], ["book.txt", "TXT"]]
`

However, when I render the gitbook version of the book, I end up losing the new entries, i.e. the docx and txt file in the html format. 

It should create a 
`"download": ["book.pdf", "book.epub", "book.docx", "book.txt"],`

line in the `index.html`, but it becomes

`"download": ["book.pdf", "book.epub"],`

so something appears to be hard-coded here.  Of course, if I manually add the missing elements from the list, the gitbook will look as expected, but I am curious why this is lost in rendering.

**Comment by yihui** [comment]
The [issue guide](new) asked you to provide a minimal reproducible example, and you didn't (and also deleted the issue guide). Please follow the issue guide more carefully in the future. Thanks!

I cannot reproduce your issue with [the bookdown-demo project](/rstudio/bookdown-demo) and `_output.yml`:

```yaml
bookdown::gitbook:
  config:
    download: [ ["book.pdf", "PDF"], ["book.epub", "EPUB"], ["book.docx", "Word"], ["book.txt", "TXT"]]
```

![image](https://user-images.githubusercontent.com/163582/72569850-012ec380-3881-11ea-941e-60a06c468b59.png)
