### ISSUE TITLE
Command line building of book

### ISSUE THREAD

**Issue by csgillespie** [rstudio/bookdown#90]
I have a book which has

```
  bookdown::pdf_book:
    includes:
      in_header: preamble.tex
    keep_tex: yes
```
in `_bookdown.yml`. When I click `knit`, the pdf version builds fine. When I run

```
bookdown::render_book("index.Rmd", output_format = "pdf_document")
```

The file `preamble.tex` isn't included and the latex part breaks.
