### ISSUE TITLE
Options specific to some output need to be at top-level

### ISSUE THREAD

**Issue by umarcor** [rstudio/bookdown#918]
When trying to use options such as `biblio-title`, `margin-left` or `margin-right` in the preamble of the index/root `Rmd` file, I found that only adding them at the top-level would work:

```yml
site: bookdown::bookdown_site
documentclass: report
lof: yes
bibliography: ["Rmd/refs.bib"]
csl: Rmd/ieee.csl
link-citations: yes
biblio-title: References
margin-left: 35mm
margin-right: 35mm
output:
  bookdown::gitbook:
    config:
      info: no
    bookdown::pdf_book:
      toc_depth: 4
      includes:
        in_header: Rmd/preamble.tex
      latex_engine: xelatex
      citation_package: biblatex
      keep_tex: yes
    bookdown::epub_book: default
```

Instead, I would have expected those keys to be supported in `output > bookdown::pdf_book:`:

```yml
site: bookdown::bookdown_site
documentclass: report
lof: yes
bibliography: ["Rmd/refs.bib"]
csl: Rmd/ieee.csl
link-citations: yes
output:
  bookdown::gitbook:
    config:
      info: no
    bookdown::pdf_book:
      toc_depth: 4
      includes:
        in_header: Rmd/preamble.tex
      latex_engine: xelatex
      citation_package: biblatex
      keep_tex: yes
      biblio-title: References
      margin-left: 35mm
      margin-right: 35mm
    bookdown::epub_book: default
```

However, if I use the latter format, those options seem to be silently ignored.

Find full example repo: [LarsAsplund/github-facts](https://github.com/LarsAsplund/github-facts/).
