### ISSUE TITLE
pdf_document2 ignores yaml arguments

### ISSUE THREAD

**Issue by wmay** [rstudio/bookdown#919]
`pdf_document2` ignores toc and number_sections arguments. The pdf generated by this R Markdown snippet should include a table of contents and numbered sections, but it doesn't:

```
---
title: "Test"
output:
  bookdown::pdf_document2:
    toc: true
    number_sections: true
---

# s1

# s2

## s2p1

## s2p2
```

However, the same snippet using rmarkdown's `pdf_document` works as expected:

```
---
title: "Test"
output:
  pdf_document:
    toc: true
    number_sections: true
---

# s1

# s2

## s2p1

## s2p2
```

I've tried this with both the CRAN and Github versions of bookdown. On my computer `xfun::session_info('bookdown')` returns

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS

Locale:
  LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
  LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
  LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
  LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

Package version:
  base64enc_0.1.3 bookdown_0.20.2 digest_0.6.25   evaluate_0.14   glue_1.4.1      graphics_4.0.2 
  grDevices_4.0.2 highr_0.8       htmltools_0.5.0 jsonlite_1.7.0  knitr_1.29      magrittr_1.5   
  markdown_1.1    methods_4.0.2   mime_0.9        rlang_0.4.7     rmarkdown_2.3   stats_4.0.2    
  stringi_1.4.6   stringr_1.4.0   tinytex_0.25    tools_4.0.2     utils_4.0.2     xfun_0.16      
  yaml_2.2.1     
```

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('bookdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/bookdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.
