### ISSUE TITLE
Having file with only PART header will cause wrong html structure in previous chapter

### ISSUE THREAD

**Issue by cderv** [rstudio/bookdown#974]
This comes from an investigation on an issue reported in https://github.com/tidymodels/TMwR/issues/75

# Step to reproduce 

* Use the book demo
* Add a `PART.Rmd` file with this content
```md
# (PART) Content {-}

```
* Use this `_bookdown.yml`
```yaml
book_filename: "bookdown-demo"
language:
  ui:
    chapter_name: "Chapter "
delete_merged_file: true
rmd_files: [
  "index.Rmd",
  "01-intro.Rmd",
  "PART.Rmd",
  "02-literature.Rmd"
]
```
* Build the book

# Issue

The chapter just before the PART header, the one call _Introduction_, will have an incorrect HTML structure leading to 
* No navigation arrow on the side
* Wrong position and formatting of the reference and footnote section
![image](https://user-images.githubusercontent.com/6791940/95748133-d51e6280-0c99-11eb-9341-42d40409737b.png)

The splitting process of **bookdown** does not handle well this case. 
The section inside `<div class 'page-inner'>` will close too soon, causing the Reference part and the navigation arrows to be included at the end of the wrong div.
