### ISSUE TITLE
pagebreak.lua content is displayed right before bibliography list

### ISSUE THREAD

**Issue by jooyoungseo** [rstudio/bookdown#995]
Currently, all the content in `pagebreak.lua` is displayed right before bibliography list in `bookdown::word_document2()` output.

Tested with Pandoc 2.10.1 and 2.11.2 on Windows.

## Reprex

``` yaml
---
output: bookdown::word_document2
bibliography: "test.bib"
nocite: "@*"
---
```

````
```{r bib, include = FALSE}
knitr::write_bib(c("knitr", "rmarkdown", "bookdown", "blogdown", "pagedown", "xfun"), file = "test.bib")
```

# References {-}
````
